name: CI/CD Pipeline - MedBill

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build the project
        run: |
          echo "Building MedBill Application"
          mkdir -p target
          echo "Build Successful!"

      - name: Build Docker image
        run: docker build -t medbill-app .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 medbill-app

      - name: CI/CD success
        run: echo "✅ CI/CD pipeline executed successfully!"
